### ISSUE TITLE
Add wifi feature?!?

### ISSUE THREAD

**Issue by quydau35** [ngohuynhngockhanh/anova#1]
hệ thống sensor của bạn có thể sử dụng wifi để giao tiếp thay cho radio thông thường không? Ở nông thôn thiếu wifi, nhưng lại rất ít nhà cao tầng cản trở thu phát wifi.

**Comment by ngohuynhngockhanh** [comment]
hehe, chỉ cần ở tầng RF2.4GHz (Radio) thông thường thôi ạ, nó dùng chung công nghệ wifi á :). Ở tầng server có thể dùng công nghệ 3G để lên Internet :). Vì 3G có thể nạp tiền từ xa qua sim nên vấn đề mạng là một vấn đề không quá khó

**Comment by quydau35** [comment]
Nếu sử dụng mạng 3G thì những vùng như Củ Chi, Long Thành (theo mình biết) sẽ ok, nhưng những vùng như Dak Nông, Kon Tum, Bảo Lộc,... sẽ tương đối khó khăn. Mình muốn biết giao thức bạn sử dụng giao tiếp giữa các thiết bị là gì, vì nếu hệ thống sensor (mỗi sensor đều có khả năng truyền phát) có thể tạo thành network riêng thì không phải phụ thuộc vào 3G hay cable ethernet nữa.
Mình cũng đang phát triển một hệ thống sensor phục vụ nông nghiệp như bạn, nhưng mình làm độc lập và không biết là nhóm bạn đã làm thành công luôn cả hệ thống server. Mình chỉ có thêm anemometer và barometer thôi, mình thiếu light intensity sensor như của nhóm bạn đã làm. Mình sử dụng hai sensor này vì mình muốn biết luồng gió và tạo data khí tượng.
Mình có thể liên lạc với nhóm bạn cụ thể hơn được không nhỉ?

**Comment by ngohuynhngockhanh** [comment]
hi, mỗi sensor sẽ kết nối tới gateway qua module nrf đó bạn :).

Còn dùng 3g/wifi là để up data từ gateway lên cloud thôi à, có thể không
cần thiết nếu dùng trong cục bộ!

Hiện tại, nhóm mình vẫn đang phát triển, mọi thông tin về dự án này khi ở
mức release được, chúng mình sẽ xuất bản trên arduino.vn - cộng đồng
arduino Việt Nam á.

Khoàng thời gian tầm tháng 6/2016 bạn nhé :). Do nhóm mình vẫn đang hoàn
thiện phần server :). Lúc có, mình sẽ thông báo rõ hơn!

Trân trọng,
Ngô Huỳnh Ngọc Khánh

Vào 15:39 Ngày 26 tháng 04 năm 2016, Nguyễn Hữu Quý Ngân <
notifications@github.com> đã viết:
